### PR TITLE
vnc support for sdk 32, 33, 34 devicefarmer/minicap

### PR DESCRIPTION
**Pull request by varundtsfi**
Right now only .so files are there with SDK version of **32, 33 and 34.**

Soon I will push the minicap.cpp files coresponding to their SDK version and update the **Android**.**mk** file and **Makefile**

### CODE REVIEW

**Comment by varundtsfi** [comment]
> NPM test check failed due to outdated build machine. I've just updated the CI config, so you can sync with master.

Hi @koral--  
I am using **Ubuntu 22.04.4 LTS**

**Review by koral-- — APPROVED** [review]

**Comment by varundtsfi** [comment]
> Unfortunately the minicap.so for android 34 results in a segmentation fault, for example on Pixel 8
> ```
> INFO: (external/MY_minicap/src/minicap_34.cpp:245) Creating SurfaceComposerClient
> INFO: (external/MY_minicap/src/minicap_34.cpp:248) Performing SurfaceComposerClient init check
> INFO: (external/MY_minicap/src/minicap_34.cpp:259) Creating virtual display
> INFO: (external/MY_minicap/src/minicap_34.cpp:266) Creating buffer queue
> INFO: (external/MY_minicap/src/minicap_34.cpp:269) Setting buffer options
> INFO: (external/MY_minicap/src/minicap_34.cpp:273) Creating CPU consumer
> INFO: (external/MY_minicap/src/minicap_34.cpp:277) Creating frame waiter
> INFO: (external/MY_minicap/src/minicap_34.cpp:281) Publishing virtual display
> 
> Segmentation fault
> ```

Can you please give it a try on Samsung devices.

**Comment by varundtsfi** [comment]
It's not device specific or OEM but when Pixel Devices got an articular patch update about that binaries are not working.

**Comment by gassion** [comment]
Can you push the corresponding minicap.cpp file? Thank you very much

**Pull request merged**
