### PR TITLE
added minicap for sdk 32,33

### PR DESCRIPTION
**Pull request by anandharaj-dotworld**

### CODE REVIEW

**Comment by varundtsfi** [comment]
@anandharaj-dotworld  the files you have provided for Android 14 was not working. Its giving 
**Segmentation fault** 
and You have not provided the minicap_34.cpp.  Please test the binaries properly before providing .

./run.sh -P 1080x2400@1080x2400/0
++ adb shell getprop ro.product.cpu.abi
++ tr -d '\r'
+ abi=arm64-v8a
++ adb shell getprop ro.build.version.sdk
++ tr -d '\r'
+ sdk=34
++ adb shell getprop ro.build.version.preview_sdk
++ tr -d '\r'
+ pre=0
++ adb shell getprop ro.build.version.release
++ tr -d '\r'
+ rel=14
+ [[ -n 0 ]]
+ [[ 0 > 0 ]]
+ (( 34 >= 16 ))
+ bin=minicap
+ apk='app_process /system/bin io.devicefarmer.minicap.Main'
+ args=
+ '[' -P = autosize ']'
+ dir=/data/local/tmp/minicap-devel
+ adb shell 'mkdir /data/local/tmp/minicap-devel 2>/dev/null || true'
+ adb push libs/arm64-v8a/minicap /data/local/tmp/minicap-devel
libs/arm64-v8a/minicap: 1 file pushed, 0 skipped. 117.6 MB/s (723176 bytes in 0.006s)
+ '[' -e jni/minicap-shared/aosp/libs/android-14/arm64-v8a/minicap.so ']'
+ '[' -e jni/minicap-shared/aosp/libs/android-34/arm64-v8a/minicap.so ']'
+ adb push jni/minicap-shared/aosp/libs/android-34/arm64-v8a/minicap.so /data/local/tmp/minicap-devel
jni/minicap-shared/aosp/libs/android-34/arm64-v8a/minicap.so: 1 file pushed, 0 skipped. 155.3 MB/s (135328 bytes in 0.001s)
+ adb shell LD_LIBRARY_PATH=/data/local/tmp/minicap-devel /data/local/tmp/minicap-devel/minicap -P 1080x2400@1080x2400/0
PID: 24004
INFO: Using projection 1080x2400@1080x2400/0
INFO: (external/MY_minicap/src/minicap_34.cpp:394) In Android 34
INFO: (external/MY_minicap/src/minicap_34.cpp:245) Creating SurfaceComposerClient
INFO: (external/MY_minicap/src/minicap_34.cpp:248) Performing SurfaceComposerClient init check
INFO: (external/MY_minicap/src/minicap_34.cpp:259) Creating virtual display
INFO: (external/MY_minicap/src/minicap_34.cpp:266) Creating buffer queue
INFO: (external/MY_minicap/src/minicap_34.cpp:269) Setting buffer options
INFO: (external/MY_minicap/src/minicap_34.cpp:273) Creating CPU consumer
INFO: (external/MY_minicap/src/minicap_34.cpp:277) Creating frame waiter
INFO: (external/MY_minicap/src/minicap_34.cpp:281) Publishing virtual display
Segmentation fault

**Comment by KishanDasani** [comment]
is there any update on this? is it possible to get .so files for SDK 31 to 34 anytime soon?

**Comment by koral--** [comment]
This PR doesn't pass the checks.
They both have to be positive ✅

**Comment by varundtsfi** [comment]
We can close this PR as following PR got merged with the same fix.
https://github.com/DeviceFarmer/minicap/pull/58

**Pull request closed without merging**
